### ISSUE TITLE
`jimage` library fails to load when the app's file path contains Hebrew characters on Windows

### ISSUE THREAD

**Issue by zacharee** [hydraulic-software/conveyor#120]
**Describe the bug**
Using `conveyor make windows-app` in a Compose JVM project throws the following error when the executable's path has Unicode characters in it.

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class jdk.internal.module.SystemModuleFinders$SystemImage
        at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.findImageLocation(SystemModuleFinders.java:429)
        at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.read(SystemModuleFinders.java:483)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:809)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:741)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:665)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no jimage in system library path: C:\Users\×š×™× ×©×’×›×”×“\scoop\apps\bifrost\current\bin [in thread "main"]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2408)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
        at java.base/java.lang.System.loadLibrary(System.java:2015)
        at java.base/jdk.internal.jimage.NativeImageBuffer$1.run(NativeImageBuffer.java:42)
        at java.base/jdk.internal.jimage.NativeImageBuffer$1.run(NativeImageBuffer.java:40)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.base/jdk.internal.jimage.NativeImageBuffer.<clinit>(NativeImageBuffer.java:39)
        at java.base/jdk.internal.jimage.BasicImageReader.<init>(BasicImageReader.java:97)
        at java.base/jdk.internal.jimage.ImageReader$SharedImageReader.<init>(ImageReader.java:229)
        at java.base/jdk.internal.jimage.ImageReader$SharedImageReader.open(ImageReader.java:243)
        at java.base/jdk.internal.jimage.ImageReader.open(ImageReader.java:67)
        at java.base/jdk.internal.jimage.ImageReader.open(ImageReader.java:71)
        at java.base/jdk.internal.jimage.ImageReaderFactory$1.apply(ImageReaderFactory.java:70)
        at java.base/jdk.internal.jimage.ImageReaderFactory$1.apply(ImageReaderFactory.java:67)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at java.base/jdk.internal.jimage.ImageReaderFactory.get(ImageReaderFactory.java:61)
        at java.base/jdk.internal.jimage.ImageReaderFactory.getImageReader(ImageReaderFactory.java:85)
        at java.base/jdk.internal.module.SystemModuleFinders$SystemImage.<clinit>(SystemModuleFinders.java:385)
        ... 8 more
```

**To Reproduce**

1. Clone https://github.com/zacharee/SamloaderKotlin.
2. Run `conveyor make windows-app` (the config task depends on `build` so it should automatically build the source).
3. Move the app contents to a folder named `ךינשגכהד`.
4. Try to run the executable from CMD.
5. A similar error to above will be thrown and the app won't run.

**Expected behavior**
The system library path should correctly encode the Hebrew characters and the app should load `jimage` and launch.

**Desktop (please complete the following information):**
 - OS: Windows 11 (execution), macOS 15 (compilation)
 - Conveyor: 14.3.

**Additional context**
I think this involves Conveyor since it's handling the Windows packaging. I tried the various encoding options available in the documentation to try to force UTF-8, but they had no effect.

**Comment by zacharee** [comment]
Using Java 21 seems to solve this, actually. I thought Java 18 was supposed to have proper support for Unicode, but I guess not.

**Comment by mikehearn** [comment]
Great to hear you got it solved! Conveyor does put the process into UTF-8 mode by default. Arguably maybe it shouldn't, but with the shift to UTF-8 everywhere it seemed forward looking. Java 18 was the first version to switch the JVM to UTF-8 on Windows by default, but it's possible there were bug fixes to that support later.
