### ISSUE TITLE
Cannot start demo electron app

### ISSUE THREAD

**Issue by t3rrey** [hydraulic-software/conveyor#124]
When I attempt to start the basic demo electron app it throws errors
 `conveyor generate electron test-app`
 
 Then run `npm run start`

I get this error

```
npm run start

> test-app@1.0 start
> electron .

App threw an error during load
Error: Failed to load shared library: dlopen(/Users/lachlan/Frameworks/libconveyor.dylib, 0x0006): tried: '/Users/lachlan/Frameworks/libconveyor.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/lachlan/Frameworks/libconveyor.dylib' (no such file), '/Users/lachlan/Frameworks/libconveyor.dylib' (no such file)
    at obj.load (/Users/lachlan/code/test-app/node_modules/koffi/index.js:480:27)
    at Object.<anonymous> (/Users/lachlan/code/test-app/node_modules/@hydraulic/conveyor-control/index.js:59:13)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:13801)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/lachlan/code/test-app/main.js:7:34)
^C/Users/lachlan/code/test-app/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGINT
```

node `20.13.1`

npm `10.8.2`

@hydraulic/conveyor 15.0.0

**Comment by mikehearn** [comment]
Sorry about that! Try `conveyor run` instead. The problem is that since recently the template code assumes it's running inside an app packaged inside Conveyor which isn't the case when you use `npm run start`. This is an oversight and we'll update the template to handle both cases.

**Comment by mikehearn** [comment]
Please update to version 1.2.0 of `@hydraulic/conveyor-control` and the issue should be fixed.
